### ISSUE TITLE
[Bug]: Unresponsive keyboard and trackpad

### ISSUE THREAD

**Issue by athithya12** [asus-linux-drivers/asus-numberpad-driver#119]
### Describe the bug

I installed the dev version successfully. Post-reboot, I was able to login successfully. After logging in, the screen freezes and the keyboard and the trackpad becomes unresponsive. I also tried plugging in a mouse, but no luck.

I'm using ASUS Zenbook 14 (i5-1240p Alder-lake processor)

### Expected behavior

The boot should continue normally instead of freezing.

### Relevant log output

```shell
Unable to check logs due to frozen keyboard.
```

### Desktop

- Distro [Fedora]
- Kernel [Fedora 38]

**Comment by ldrahnik** [comment]
@athithya12 Hello, at first thank you for creating an issue. When you run driver manually vith LOG=DEBUG as is described in Troubleshoting heading in README.md, it works as expected? Strach loga 

When you run

**Comment by ldrahnik** [comment]
@athithya12 Can be reopened.
