### ISSUE TITLE
[Bug]: doesn't work on kubuntu

### ISSUE THREAD

**Issue by complib2891** [asus-linux-drivers/asus-numberpad-driver#120]
### Describe the bug

doesn't seems to work on kubuntu

### Expected behavior

to work on kubuntu?

### Relevant log output

```shell
$ journalctl -u asus_touchpad_numpad@user

-- Boot 6ef3e8adb6e242338206a4ab865d2cb4 --
Jun 08 20:27:09 zenbook systemd[1]: Started Asus Touchpad to Numpad Handler.
Jun 08 20:27:14 zenbook systemd[1]: asus_touchpad_numpad@user.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 20:27:14 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:14 zenbook systemd[1]: asus_touchpad_numpad@user.service: Scheduled restart job, restart counter is at 1.
Jun 08 20:27:14 zenbook systemd[1]: Stopped Asus Touchpad to Numpad Handler.
Jun 08 20:27:14 zenbook systemd[1]: Started Asus Touchpad to Numpad Handler.
Jun 08 20:27:15 zenbook systemd[1]: asus_touchpad_numpad@user.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 20:27:15 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Scheduled restart job, restart counter is at 2.
Jun 08 20:27:16 zenbook systemd[1]: Stopped Asus Touchpad to Numpad Handler.
Jun 08 20:27:16 zenbook systemd[1]: Started Asus Touchpad to Numpad Handler.
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Scheduled restart job, restart counter is at 3.
Jun 08 20:27:16 zenbook systemd[1]: Stopped Asus Touchpad to Numpad Handler.
Jun 08 20:27:16 zenbook systemd[1]: Started Asus Touchpad to Numpad Handler.
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 20:27:16 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Scheduled restart job, restart counter is at 4.
Jun 08 20:27:17 zenbook systemd[1]: Stopped Asus Touchpad to Numpad Handler.
Jun 08 20:27:17 zenbook systemd[1]: Started Asus Touchpad to Numpad Handler.
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Scheduled restart job, restart counter is at 5.
Jun 08 20:27:17 zenbook systemd[1]: Stopped Asus Touchpad to Numpad Handler.
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Start request repeated too quickly.
Jun 08 20:27:17 zenbook systemd[1]: asus_touchpad_numpad@user.service: Failed with result 'exit-code'.
Jun 08 20:27:17 zenbook systemd[1]: Failed to start Asus Touchpad to Numpad Handler.
```

### Desktop

- Program version 2.7.3
- Distro kubuntu jammy 22.04.2
- Kernel 5.15.0-73-generic

**Comment by ldrahnik** [comment]
Hello there, thank you for creating an issue. Please attach content of driver log file located here `/var/log/asus_touchpad_numpad-driver/error.log`.

**Comment by ldrahnik** [comment]
@complib2891 Which groups have your user? (command `groups`), which groups have your user after executing `sudo install.sh --user` script and reboot (is required!).

**Comment by complib2891** [comment]
erm, so now i uninstall first, then run `sudo install.sh` and save the log?

**Comment by ldrahnik** [comment]
- command `groups` (attach here output)
- `sudo install.sh --user` + reboot + `groups` (attach here output)

then please try as root

- run `sudo ./uninstall.sh --user`
- run `sudo ./install.sh` # installed under root
- attach log here `/var/log/asus_touchpad_numpad-driver/error.log`

**Comment by complib2891** [comment]
i've `sudo ./uninstall.sh --user` then `sudo ./install.sh` then reboot, the touchpad seems to work now. just that the brightness of the keypad sequence is not toggling, rather something like reduce brightness, then kept on increase brightness, scared it will break the hardware, but the touchpad is working, thank you very much, i guess i should go without `--user` in the first place. not always using the keypad anyway, it should be fine i suppose.

the new install.sh log here https://gist.github.com/complib2891/5d2388bf25434763566d6fdc8715a707

Again, thanks A LOT, i really want the touchpad to work in kubuntu.. :)

**Comment by ldrahnik** [comment]
@complib2891 Brightness should be incresead continually in endless cycle. Is it not increased continually for your hardware?

**Comment by ldrahnik** [comment]
@complib2891 Np, put a star if you like :) and you do not hesitate me so feel free create new issues, glad to help you

**Comment by ldrahnik** [comment]
@complib2891 I have added required install when driver adds groups to user (`i2c, uinput & input`), should be fine have feedback it works or not:

> command groups (attach here output)
> sudo install.sh --user + reboot + groups (attach here output)

**Comment by complib2891** [comment]
> @complib2891 Brightness should be incresead continually when you hold the finger on the top left icon in endless cycle. Not toggling! Is it not increased continually for your hardware?

it didn't cycle, i think it's stuck at max brightness when pressing top left, then i have to turn the keypad off

**Comment by complib2891** [comment]
> 



> @complib2891 I have added required reboot when driver adds groups to user (`i2c, uinput & input`), should be fine have feedback it works or not:

so my username should have these i2c, uinput and input ? , when using `--user` i assume.

**Comment by ldrahnik** [comment]
@complib2891

> so my username should have these i2c, uinput and > input ? , when using --user i assume

Yeah, thé code on install.sh should do that

**Comment by ldrahnik** [comment]
> it didn't cycle, i think it's stuck at max brightness when pressing top left, then i have to turn the keypad off

@complib2891 Does have your sudo user `i2c` group? Please attach `/var/log/asus_touchpad_numpad-driver/error.log` when installed as root.

**Comment by complib2891** [comment]
> > it didn't cycle, i think it's stuck at max brightness when pressing top left, then i have to turn the keypad off
> 
> @complib2891 Does have your sudo user `i2c` group? Please attach `/var/log/asus_touchpad_numpad-driver/error.log` when installed as root.

sorry for the late reply, i don't see i2c/input/uinput group for the sudo user. I'll try out 2.7.4? just found another weird issue, the touchpad driver doesn't seems to activated fully (i must press hard on the pad to trigger a click instead of soft touching the pad) only after I turn on the keypad, only then i can soft-touch to trigger a click.

**Comment by ldrahnik** [comment]
@complib2891 Please attach `/var/log/asus_touchpad_numpad-driver/error.log` when is driver installed under root. Thank you.
