### ISSUE TITLE
Keyboard Layout Problem

### ISSUE THREAD

**Issue by Tahinli** [asus-linux-drivers/asus-numberpad-driver#125]
Normally i use Turkish Q keyboard. when i press "dot" in numpad, it prints "comma"
If i switch to the English keyboard. there is no problem.

Here are the logs:

[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11905411/error.log)

possible but definitely bad solution: dot button should trigger to slash instead of dot, because of keyboard structure differences between Turkish and English keyboards. but this will break English keyboards,

**Comment by ldrahnik** [comment]
@Tahinli Replicated, thank you for report

**Comment by ldrahnik** [comment]
@Tahinli Every layout at this moment relies on the fact that `KEY_KPxyz` keys are equal in all layouts and are not rebinded. Workaround untill will be solved is to use "." instead of EV_KEY.KEY_KPDOT inside layout file which is used.

**Comment by ldrahnik** [comment]
@Tahinli `git pull` latest master

**Comment by ldrahnik** [comment]
@Tahinli Because send one key event is less then send unicode number of the same key via Shift+Ctrl+U+number (5 key events vs 1)

**Comment by Tahinli** [comment]
> @Tahinli Because send one key event is less then send unicode number of the same key via Shift+Ctrl+U+number (5 key events minimum vs 1)

Makes sense, thanks

**Comment by Tahinli** [comment]
it crashes, when i print "+", "." , "-", "*", "/", "="

i will try to capture logs

**Comment by Tahinli** [comment]
here my service file
[asus_touchpad_numpad@.service.txt](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11906543/asus_touchpad_numpad%40.service.txt)

**Comment by ldrahnik** [comment]
@Tahinli wrong variable name is there, `xdisplay` vs `display`, do you want make PR?

**Comment by Tahinli** [comment]
> @Tahinli wrong variable name is there, `xdisplay` vs `display`, do you want make PR?

i would be very happy.

**Comment by Tahinli** [comment]
strange thing is fedora didn't show me black screen even standartinput is not commented

**Comment by ldrahnik** [comment]
@Tahinli Maybe this misstyped variable name, bug created by me in version 2.7.4 is responsible for that blackscreen.

**Comment by Tahinli** [comment]
> @Tahinli wrong variable name is there, `xdisplay` vs `display`, do you want make PR?

maybe i did wrong but, can you check

 https://github.com/Tahinli/asus-numberpad-driver/commit/123f16f106ebb5933c994dec0c2534d629280af4

don't you mean that.

**Comment by ldrahnik** [comment]
@Tahinli 
> maybe i did wrong but, can you check

Is now display variable filled ok to service?

> don't you mean that.

> because still xdisplay is not valid

I do not know, I will wait until you will analyze what has to be in service to fail during booting.

**Comment by ldrahnik** [comment]
@Tahinli Change even this please

`cat asus_touchpad.X11.service | CONFIG_FILE_DIR="$CONFIG_FILE_DIR/" USER=$RUN_UNDER_USER LAYOUT=$model XDISPLAY=$xdisplay XAUTHORITY=$xauthority envsubst '$LAYOUT $XAUTHORITY $CONFIG_FILE_DIR' > /etc/systemd/system/asus_touchpad_numpad@.service`

to 

`cat asus_touchpad.X11.service | CONFIG_FILE_DIR="$CONFIG_FILE_DIR/" USER=$RUN_UNDER_USER LAYOUT=$model XDISPLAY=$xdisplay XAUTHORITY=$xauthority envsubst '$LAYOUT $XAUTHORITY $XDISPLAY $CONFIG_FILE_DIR' > /etc/systemd/system/asus_touchpad_numpad@.service`

**Comment by Tahinli** [comment]
oaky display worked. I'm happy that, also black screen is resolved. I will try with fresh install again for black screen.

**Comment by ldrahnik** [comment]
@Tahinli 
> display worked. I'm happy that, also black screen is resolved. I will try with fresh install again for black screen.

Nice, let me know.

**Comment by Tahinli** [comment]
> @Tahinli
> 
> > display worked. I'm happy that, also black screen is resolved. I will try with fresh install again for black screen.
> 
> Nice, let me know.

happy news. no black screen

**Comment by ldrahnik** [comment]
@Tahinli So now is driver log clear? No error there? You could now try IMHO best option of config value `enabled_touchpad_pointer=3`, does it work? Does it also fixed problem with toggling calculator by swiping top left icon?

**Comment by Tahinli** [comment]
> @Tahinli So now is driver log clear? No error there? You could now try IMHO best option of config value `enabled_touchpad_pointer=3`, does it work? Does it also fixed problem with toggling calculator by swiping top left icon?

I'm not available now. Aproximately after 8 hours, i can check. Funny thing is calculator was working afaik. I dont know why but even without update, after fresh install there were no calculator or slow opening issue. When i said calculator wasnt working and wayland was opening slowly, there should have been another thing. Like i said lastly there were no issue. I will come with logs and much more verified information when i am available

**Comment by Tahinli** [comment]
Wayland Fresh install Fedora, I installed stylus driver first, then reboot, installed numpad, then reboot. Here the logs.
When i swiped for calculator, it crashed
[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11923194/error.log)

**Comment by Tahinli** [comment]
Last few days i installed fedora maybe over 10 times. how every setup can show different results, i will lost my mind

**Comment by ldrahnik** [comment]
@Tahinli Head up. Error in the log does make sense. It was the first attempt on Wayland? I will react tomorrow.

**Comment by Tahinli** [comment]
ldrahnik@gmail.com this is your mail right, if it is, can i use it to communicate with you instead of spamming unrelated things under issues.

I sent a mail 6/6/23. it was about stylus pen and didn't know what to do that time (later i solved, it was hardware issue and now  there is no problem), you didn't send any mail after that, you could be busy no problem, is this your mail right ?

**Comment by ldrahnik** [comment]
@Tahinli Error from the last attached log should be fixed,`git pull` latest master.

**Comment by Tahinli** [comment]
> @Tahinli Error from the last attached log should be fixed,`git pull` latest master and confirm please.

i didn't try it with fresh install but, 

> git pull
> sudo ./install

then reboot

no crash but no calculator

[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11923695/error.log)

**Comment by ldrahnik** [comment]
@Tahinli the same error as is displayed in log ```(process:3619): dconf-WARNING **: 02:17:34.262: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY`` is shown when you run in terminal this command for example?

```
           (sudo) gsettings set org.gnome.settings-daemon.plugins.media-keys calculator-static [\'\']
```

**Comment by Tahinli** [comment]
still it's not openingi and here the logs
[loggy.txt](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11925558/loggy.txt)

**Comment by ldrahnik** [comment]
@Tahinli I need output of mentioned command from your terminal. Sorry for confusion.

**Comment by Tahinli** [comment]
no output
![Screenshot from 2023-07-01 13-32-07](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/a54ab429-c30e-4f51-96ac-c375fa4321a4)

**Comment by ldrahnik** [comment]
@Tahinli Please reinstall (uninstall, then install) the driver, reboot And do not(!!) even activate NumberPad and please attach driver log `/var/log/asus_touchpad_numpad-driver/error.log`

**Comment by ldrahnik** [comment]
@Tahinli Then please activate / deactivate and attach log again whether error shown up.

**Comment by Tahinli** [comment]
[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11925821/error.log)

[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11925823/error.log)

**Comment by ldrahnik** [comment]
@Tahinli 

And `gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true` and `gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false` throw error it terminal or not? What is in variable DISPLAY inside your terminal `echo $DISPLAY`?

**Comment by Tahinli** [comment]
![Screenshot from 2023-07-01 16-42-24](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/964cdb70-d88d-45af-8769-ce1dc6e79f4f)

**Comment by ldrahnik** [comment]
@Tahinli Looks like driver detected wayland, so was used service without variable $DISPLAY and then gsetting could not work because had no XDISPLAY but terminal has this variable.  I am confused. Do you use wayland? Does have this change effect? So you can not tap to click via touchpad? On wayland?

**Comment by Tahinli** [comment]
I'm in wayland, normally i use tap to click but now it's disable probably because of command that you send.

**Comment by ldrahnik** [comment]
@Tahinli please comment out these lines `set_touchpad_prop_tap_to_click(0|1)` in activate and deactivate functions and reinstall, so this function will not be used. For check my prediction is correct :)

**Comment by Tahinli** [comment]
[error.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11929357/error.log)
[errorrrr.log](https://github.com/asus-linux-drivers/asus-numberpad-driver/files/11929358/errorrrr.log)


no calculator still

**Comment by ldrahnik** [comment]
@Tahinli Attached error has nothing to do with toggling calculator, for debugging toggling calculator try manually run script for toggling first located in directory where is NumberPad installed: `bash /usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh`, then check key `XF86Calculator` is send always when by using top left icon on activated Numberpad with running `libinput debug-events` listener on background, you should see ` ``event23  KEYBOARD_KEY            +12.282s	KEY_CALC (140) pressed
 event23  KEYBOARD_KEY            +12.282s	KEY_CALC (140) released```, after that check via `dconf` block of added custom shortcuts - should be there only 1 NumberPad record for toggling calculator open dconf -> path is `/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings`. Then it should work.

**Comment by ldrahnik** [comment]
@Tahinli This record you should have there

![Screenshot from 2023-07-02 13 54 32@2x](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/3233644/0c323d18-ed01-4641-97a1-9c2b1befaf2a)

**Comment by Tahinli** [comment]
> @Tahinli Nice, error missed when are lines commented out. But attached error has nothing to do with toggling calculator, for debugging toggling calculator try manually run script for toggling first located in directory where is NumberPad installed: `bash /usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh`, then check key `XF86Calculator` is send always when you do slide gesture from top left icon on activated Numberpad with running `libinput debug-events` listener on background, you should see
> 
> ```
> event23  KEYBOARD_KEY            +12.282s	KEY_CALC (140) pressed
>  event23  KEYBOARD_KEY            +12.282s	KEY_CALC (140) released\
> ```
> 
> after that check via `dconf` block of added custom shortcuts - should be there only 1 NumberPad record for toggling calculator open dconf -> path is `/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings`. Then it should work.


Firstly sorry for late, i have many exams.
> bash /usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh
it gave no output and no calculator.
![Screenshot from 2023-07-04 03-38-01](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/0ab5dd02-7f31-400d-b68d-20d79e97b709)


and swiping top left button triggers key_calc as you said, so there should be another problem instead of your driver.


here is my dconf read output.
![Screenshot from 2023-07-04 03-41-25](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/3f7e4e2b-ebe0-4c71-8391-3b6baf7a0d64)

**Comment by ldrahnik** [comment]
@Tahinli Which calculator Fedora uses? Is it `gnome-calculator`?  You can cat the installed script (`cat /usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh`):

`#!/bin/bash

if [[ $(pgrep -lf gnome-calculator) ]]; then
	killall gnome-calculator &>/dev/null &
else
	gnome-calculator &>/dev/null &
fi`

and debug.

**Comment by ldrahnik** [comment]
@Tahinli Had you time try it?

**Comment by Tahinli** [comment]
> @Tahinli Had you time try it?

Tomorrow i hope

**Comment by Tahinli** [comment]
![Screenshot from 2023-07-12 02-03-19.png](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/f5ae1de5-20e6-4762-aa09-9f89d860a370)

**Comment by ldrahnik** [comment]
@Tahinli In install script `install.sh` is condition for this, code below has to be true in your laptop in case Elementary script is installed. Test it please:

```
if [[ $(type flatpak 2>/dev/null && flatpak list | grep io.elementary.calculator 2>/dev/null) ]]; then
            echo "io.elementary.calculator here"
```

**Comment by Tahinli** [comment]
> @Tahinli In install script `install.sh` is condition for this, code below has to be true in your laptop in case Elementary script is installed. Test it please:
> 
> ```
> if [[ $(type flatpak 2>/dev/null && flatpak list | grep io.elementary.calculator 2>/dev/null) ]]; then
>             echo "io.elementary.calculator here"
> ```

I wrote this in shell script (and added fi to end of the line)

it returned 

> io.elementary.calculator here

**Comment by Tahinli** [comment]
when i did 

> flatpak run io.elementary.calculator

it says not installed.

**Comment by ldrahnik** [comment]
@Tahinli `flatpak list | grep io.elementary.calculator` output is?

**Comment by Tahinli** [comment]
I just have few apps

![image](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/e45a5063-3f30-4224-a044-6cbf118decdb)

**Comment by ldrahnik** [comment]
@Tahinli Will check tommorow, late night here.

**Comment by ldrahnik** [comment]
@Tahinli Do the same as me please in your terminal and post screenshot.

![Screenshot from 2023-07-12 11 04 43@2x](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/3233644/f0786de1-e1d7-4e7d-ac30-e5a7323d00ae)

`

**Comment by Tahinli** [comment]
Sorry, fedora broke itself first then broke me again, i had to reinstall. i'm in wayland gnome again. i don't know if it's important

![image](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/96421894/402d9efd-cde5-4db4-bea2-c2c330a869ec)

**Comment by ldrahnik** [comment]
@Tahinli I close this issue as last unresolved gsettings error is in discussion in [this issue](https://github.com/asus-linux-drivers/asus-numberpad-driver/issues/130)  and for shortcuts looks like nothing wrong in driver code.
