### ISSUE TITLE
[Feature Request] Refactor to new name asus-numberpad-driver

### ISSUE THREAD

**Issue by kamack38** [asus-linux-drivers/asus-numberpad-driver#131]
### Short Description

Since the project name changed to `asus-numberpad-driver` the install path shouldn't be `/usr/share/asus_touchpad_numpad-driver/`, but it should be `/usr/share/asus-numberpad-driver/`

### New dependencies

No

**Comment by guilhem** [comment]
it works :)

**Comment by ldrahnik** [comment]
@kamack38 Done, needs to be changed for arch package.

**Comment by kamack38** [comment]
I'll take care of this after Wednesday.

**Comment by kamack38** [comment]
The AUR package should be working now.

**Comment by ldrahnik** [comment]
@kamack38 Nice. Is possible select even unicode And non unicode layout variant? All are predefined in repository, newly.

**Comment by ldrahnik** [comment]
@kamack38 From install scripts:

```
NumberPad layout

Are predefined 2 variants of numberpad layouts for each laptop:
  - Standard is recommended to use, the keys except percent and hash tag are send directly but layout is not resistant to overbinding these keys to something else and that is reason why exist second version
  - Unicode send keys like unicode chars except backspace and enter using shortcut Ctrl+Shift+U+<sequence of number keys>
```
