### ISSUE TITLE
[Bug]: When the driver is clicked on the ubuntu login screen, three numbers will be displayed

### ISSUE THREAD

**Issue by Zijian050820** [asus-linux-drivers/asus-numberpad-driver#133]
### Describe the bug

When the driver is clicked on the ubuntu login screen, three numbers will be displayed

### Expected behavior

When the driver is clicked on the ubuntu login screen, three numbers will be displayed

### Desktop

- Program version [e.g. 57c742a]
- Distro [e.g. ubuntu]
- Kernel [e.g. 5.18.15]

**Comment by Zijian050820** [comment]
When using numberpad on the ubuntu login screen, three identical numbers appear on the number screen once clicked

**Comment by ldrahnik** [comment]
@Zijian050820 Hello there! Thank you for letting me know. Unfortunatelly without logs (driver log primary) and description about used environment (Ubuntu version, wayland/X11, keyboard layout, ..) I will have to close this issue as u unfounded.

**Comment by ldrahnik** [comment]
Can be reopened.
