### ISSUE TITLE
[Bug]: % key types 25, and swipe to open calculator doesn't work.

### ISSUE THREAD

**Issue by Octopus1348** [asus-linux-drivers/asus-numberpad-driver#147]
### Describe the bug

I have the `up5401ea` layout (my touchpad looks the same like in it's picture), and it types `,` instad of `.` and the `%` key types `25`.
When I try installing the `XF86Calculator` key toggling script, it gives `Permission denied` errors, so I added sudo here and there, but it still doesn't open the calculator, even after a reboot.

### Expected behavior

When I press `.`, it should type `.` instead of `,`, but that's not too big of a problem. When I type `%`, it should type `%`, and not `25`
When I swipe, it should open a calculator window. I installed this driver long ago, and it worked with that. Now it's broken.

### Relevant log output
Output with unmodified install_calc_toggle.sh (I manually translated these errors to English, so it might not be perfect):

```shell

Do you want try to install toggling script for XF86Calculator key? [y/N]y

Detected gnome-calculator
Setting up for gnome-calculator
cp: '/usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh' regular file couldn't be created: Permission denied
chmod: '/usr/share/asus_touchpad_numpad-driver/scripts/calculator_toggle.sh' changing permissions: Operation not permitted
Toggling script for calculator app gnome-calculator has been installed.
```

Output with my modified install_calc_toggle.sh:

```
Do you want try to install toggling script for XF86Calculator key? [y/N]y

Detected gnome-calculator
Setting up for gnome-calculator
Toggling script for calculator app gnome-calculator has been installed.
```

### Desktop

- Program version: befd213
- Distro: Ubuntu
- Kernel: 6.5.0-10-generic

**Comment by ldrahnik** [comment]
@Octopus1348 About "%" it looks like you are not able send Unicode characters with CTRL+SHIFT+U25 -> `%`. Check it. Workaround is to use in layout `[EV_KEY.KEY_LEFTSHIFT, EV_KEY.KEY_KP5]]` for "%" but IMHO is definitely the preferred make-to-work shortcut for Unicode chars if possible.

**Comment by ldrahnik** [comment]
@Octopus1348 About swiping when does not work toggling calc app bug was fixed, my bad I did mistake when I refactored code. Now be you after reinstall I would check first is send key via `$ sudo libinput debug-events` -> swipe -> ``` event23  KEYBOARD_KEY            +0.704s	KEY_CALC (140) pressed
 event23  KEYBOARD_KEY            +0.704s	KEY_CALC (140) released
```, exist record via screenshot: 
![Screenshot from 2023-10-27 14 31 41@2x](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/3233644/cd557831-6a28-4fb1-b91e-30e05f58bebb)
and script for toggling works manually, then it should work after install and reboot: `$ bash /usr/share/asus-numberpad-driver/scripts/calculator_toggle.sh`

**Comment by ldrahnik** [comment]
@Octopus1348 Attached error / install log would ve helpful

**Comment by ldrahnik** [comment]
@Octopus1348 Can be reopened.
