### ISSUE TITLE
[Layout Request] UM3402

### ISSUE THREAD

**Issue by Forceres** [asus-linux-drivers/asus-numberpad-driver#148]
### Layout Name

UM3402

### Your device (sudo dmidecode -s system-product-name)

Zenbook UM3402YAR_UM3402YA

**Comment by kamack38** [comment]
It is impossible for us to add a layout that we don't know what it looks like. Could you please supply a layout photo.

**Comment by ldrahnik** [comment]
@Forceres Thank you for creating the issue but as wrote @kamack38 we need more info. Layout looks like the same as is named `up5401ea`, so please try this one. If any problem occurs do not hesitate add comment here.

**Comment by ldrahnik** [comment]
Can be reopened.
