### ISSUE TITLE
ASUS Zenbook 14 UX3405MA_UX3405MA

### ISSUE THREAD

**Issue by raszt** [asus-linux-drivers/asus-numberpad-driver#166]
### Short Description

Could not automatically detect numberpad layout for your laptop.

**Comment by ldrahnik** [comment]
Hi, thank you for creating an issue. I will associate layout named `up5401ea`, is this layout correct one?

**Comment by raszt** [comment]
Hi, Yes.
Thanks in advance.


üdv
sTz
Poco F3

Lukáš Drahník ***@***.***> ezt írta (időpont: 2024. febr.
23., P 12:43):
