### ISSUE TITLE
[Layout Request] ux7602-unicode

### ISSUE THREAD

**Issue by FrancoisChaumont** [asus-linux-drivers/asus-numberpad-driver#168]
### Layout Name

ux7602-unicode

### Your device (cat /sys/devices/virtual/dmi/id/product_name)

Zenbook UX7602VI_UX7602VI

**Comment by kamack38** [comment]
For the future we would really appreciate, if you had read the issue template and filled numpad layout field (just take a picture of your numpad or find one on the Internet). Anyway here's one:
![image](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/64226248/1155a5c8-2fe9-4a23-8aab-e20534d22cba)

**Comment by kamack38** [comment]
Wait, I think `up5401ea` is the correct one, it looks identical.

**Comment by FrancoisChaumont** [comment]
> For the future we would really appreciate, if you had read the issue template and filled numpad layout field (just take a picture of your numpad or find one on the Internet). Anyway here's one: ![image](https://private-user-images.githubusercontent.com/64226248/312929706-1155a5c8-2fe9-4a23-8aab-e20534d22cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjM0MDcsIm5iZiI6MTcxMDQ2MzEwNywicGF0aCI6Ii82NDIyNjI0OC8zMTI5Mjk3MDYtMTE1NWE1YzgtMmZlOS00YTIzLThhYWItZTIwNTM0ZDIyY2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0M2EzMWE4MjQxZWQ5NDNmYTI3YzMxOTQ1NjEwYjI5MmE4M2UzNjZhMjFkYTFiYjQ4ZjllZTAzOWZmYjJlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3S7U0SBhfPXm4BoePETHSCM4hQK4uIgpOSlUBb-BcE)

Apologies, I wasn't sure how to go about all those fields.

**Comment by FrancoisChaumont** [comment]
> Wait, I think `up5401ea` is the correct one, it looks identical.

Amazing! This is the one. It works perfectly! 
Thank you so much!

**Comment by kamack38** [comment]
> > For the future we would really appreciate, if you had read the issue template and filled numpad layout field (just take a picture of your numpad or find one on the Internet). Anyway here's one: ![image](https://private-user-images.githubusercontent.com/64226248/312929706-1155a5c8-2fe9-4a23-8aab-e20534d22cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjM0MDcsIm5iZiI6MTcxMDQ2MzEwNywicGF0aCI6Ii82NDIyNjI0OC8zMTI5Mjk3MDYtMTE1NWE1YzgtMmZlOS00YTIzLThhYWItZTIwNTM0ZDIyY2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0M2EzMWE4MjQxZWQ5NDNmYTI3YzMxOTQ1NjEwYjI5MmE4M2UzNjZhMjFkYTFiYjQ4ZjllZTAzOWZmYjJlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3S7U0SBhfPXm4BoePETHSCM4hQK4uIgpOSlUBb-BcE)
> 
> Apologies, I wasn't sure how to go about all those fields.

Do you think that there's something we could do about that to make it easier for the future users?

**Comment by FrancoisChaumont** [comment]
> Do you think that there's something we could do about that to make it easier for the future users?

Maybe add some examples for values to provide based of an already existing layout for guidance/reference?

I had no clue what to put under:
- Supported Devices
- All the offsets
- All icon data

My bad on the Numpad Layout, I could have sent a picture.
