### ISSUE TITLE
[Feature Request] Fewer gestures for activating the calculator toggle

### ISSUE THREAD

**Issue by irvng-wav** [asus-linux-drivers/asus-numberpad-driver#179]
### Short Description

Currently to activate the calculator toggle with the `up5401ea` layout (don't know about the others) you have to 1. Turn on the numpad, then 2. Swipe your finger down from the calculator toggle button and then right after that, press the numpad on/off button. Here's a video:

https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/147911588/63c93de8-8303-4ebf-9121-eb8f20bab6bf

In Windows you just have to slide your finger down from the calculator toggle button without having to enable the numpad first. That automatically launches the calculator plus turns on the numpad, here's a video:

https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/147911588/f8d3382c-816a-4089-a63d-70e89b082bed

At the end of the video you can see a bug when entering a mathematical operation and then trying to close the calculator with the toggle, so even the official driver is kinda wonky lol.

It would be fantastic if the behavior of the Linux driver did that too, that you could use the calculator toggle without the need to have the numpad already on.

Thank you! 😄

**Comment by ldrahnik** [comment]
@irvng-wav Can be reopened.
