### ISSUE TITLE
[Feature Request] Gentoo support

### ISSUE THREAD

**Issue by v0llk** [asus-linux-drivers/asus-numberpad-driver#182]
### Short Description

This driver does not work on Gentoo

### Additional Info

I'm currently working on fixing it myself so I don't have to bother the dev team especially if none of them use Gentoo, I'll submit a pull request when I'm done

**Comment by ldrahnik** [comment]
Hi, the version `5.1.1` should be stable except found bug with adding shorcut for toggling calculator fixed by this commit. https://github.com/asus-linux-drivers/asus-numberpad-driver/commit/0811090180d4c456bc86489c4ed55d843f0d5b4a. PR with any changed Is very welcome. Thank you.

**Comment by ldrahnik** [comment]
@v0llk Can be reopened.
