### ISSUE TITLE
[Layout Request] G512LU

### ISSUE THREAD

**Issue by furkanzdm** [asus-linux-drivers/asus-numberpad-driver#183]
### Layout Name

G512LU

### Your device (cat /sys/devices/virtual/dmi/id/product_name)

ROG Strix G512LU_G512LU

### Supported Devices

G513

### Numpad Layout (photo/picture or code)

![asus_numkey](https://github.com/asus-linux-drivers/asus-numberpad-driver/assets/146936696/c4d959d7-fe34-455c-be06-151c56f7d1b0)

### Additional Info

Uses the same layout as G513 of G15 2022

### Acknowledgements

- [X] This layout doesn't currently exist and I have read the [Layout section](https://github.com/asus-linux-drivers/asus-numberpad-driver?tab=readme-ov-file#layouts)

**Comment by kamack38** [comment]
Doesn't the G533 layout work?

**Comment by furkanzdm** [comment]
> Doesn't the G533 layout work?

As of the moment, i get no device found error. So i assume it doesn't work.

**Comment by ldrahnik** [comment]
@furkanzdm Hi, could you please attach the entire output of the install script?

**Comment by furkanzdm** [comment]
> @furkanzdm Hi, could you please attach here the entire output of the install script?

I was using Ubuntu 6.8 lowlatency kernel, and had some driver issues with nvidia too. So switched kernel to 6.8 generic, and all is well. G513 detected as suitable layout and successfully installed. Its working completely fine at the moment.

**Comment by ldrahnik** [comment]
Can be reopened.
