### ISSUE TITLE
[Feature Request] Use systemd logging when running as a systemd service

### ISSUE THREAD

**Issue by alercah** [asus-linux-drivers/asus-numberpad-driver#214]
### Short Description

So that `journalctl -u` works correctly to filter logs from a specific unit, it would be helpful for the systemd daemon to use systemd's [logging API](https://www.freedesktop.org/software/systemd/python-systemd/journal.html).

### New dependencies

python-systemd

**Comment by ldrahnik** [comment]
@alercah Does this branch work as expected? https://github.com/asus-linux-drivers/asus-numberpad-driver/pull/215
