### ISSUE TITLE
[Bug]: install.sh fails on arch derivates due to invalid install parameter

### ISSUE THREAD

**Issue by a-sassermann** [asus-linux-drivers/asus-numberpad-driver#227]
### Describe the bug

install.sh fail at install step "wayland". The parameter "install" does not exist with pacman, -S is sufficient. 
The script terminates here due to errors

### Expected behavior

Install script should pass install step wayland without error.

### Desktop

- Program version: current master
- Distro: Manjaro Linux
- Kernel: 6.6.63-1-MANJARO

**Comment by ldrahnik** [comment]
@a-sassermann Hello, thank you, and sorry, I overlooked that. Merged.
