### ISSUE TITLE
Not Working on Asus X415ea

### ISSUE THREAD

**Issue by Foul** [asus-linux-drivers/asus-numberpad-driver#27]
i tested all combinations... but only Led is on/off and no numbers printed on screen :(
(layout is up5401ea)

**Comment by Foul** [comment]
the led (right/up) is light.. but no reaction when typing...

**Comment by kamack38** [comment]
Are you running it using `sudo`?

**Comment by Foul** [comment]
of course :)
Latest Kernel from Linux Mint 20.3

**Comment by kamack38** [comment]
Have you checked the service (`sudo systemctl status asus_touchpad_numpad.service`)?

**Comment by Foul** [comment]
i'm not on the computer right now.. il will at 14h00
for info, i tested this driver : https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver
and don't work at all (no led on/off)

**Comment by Foul** [comment]
> Have you checked the service (`sudo systemctl status asus_touchpad_numpad.service`)?

asus_touchpad_numpad.service - Asus Touchpad to Numpad Handler
     Loaded: loaded (/etc/systemd/system/asus_touchpad_numpad.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-07-13 13:58:14 CEST; 1min 2s ago
    Process: 584 ExecStartPre=/bin/sleep 2 (code=exited, status=0/SUCCESS)
   Main PID: 898 (python3)
      Tasks: 2 (limit: 4197)
     Memory: 34.7M
     CGroup: /system.slice/asus_touchpad_numpad.service
             └─898 python3 /usr/share/asus_touchpad_numpad-driver/asus_touchpad.py up5401ea 40

juil. 13 13:58:12 nathalie-VivoBook-ASUSLaptop-X415EA-X415EA systemd[1]: Starting Asus Touchpad to Numpad Handler...
juil. 13 13:58:14 nathalie-VivoBook-ASUSLaptop-X415EA-X415EA systemd[1]: Started Asus Touchpad to Numpad Handler.

**Comment by Foul** [comment]
yes !

**Comment by kamack38** [comment]
What's your operating system and kernel?

**Comment by kamack38** [comment]
Stop the service (`sudo systemctl stop asus_touchpad_numpad.service`) and clone the repo again (because of the missing layout) and run `LOG=DEBUG sudo -E ./asus_touchpad.py up5401ea 40`

**Comment by Foul** [comment]
nathalie@nathalie-VivoBook-ASUSLaptop-X415EA-X415EA:~/Téléchargements$ git clone https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver
Clonage dans 'asus-touchpad-numpad-driver'...
remote: Enumerating objects: 494, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 494 (delta 140), reused 182 (delta 123), pack-reused 267
Réception d'objets: 100% (494/494), 849.15 Kio | 708.00 Kio/s, fait.
Résolution des deltas: 100% (296/296), fait.
nathalie@nathalie-VivoBook-ASUSLaptop-X415EA-X415EA:~/Téléchargements$ cd asus-touchpad-numpad-driver/
nathalie@nathalie-VivoBook-ASUSLaptop-X415EA-X415EA:~/Téléchargements/asus-touchpad-numpad-driver$ sudo systemctl stop asus_touchpad_numpad.service
[sudo] Mot de passe de nathalie :      
nathalie@nathalie-VivoBook-ASUSLaptop-X415EA-X415EA:~/Téléchargements/asus-touchpad-numpad-driver$ LOG=DEBUG sudo -E ./asus_touchpad.py up5401ea 40
Traceback (most recent call last):
  File "./asus_touchpad.py", line 31, in <module>
    model_layout = importlib.import_module('numpad_layouts.'+ model)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'numpad_layouts.up5401ea'
nathalie@nathalie-VivoBook-ASUSLaptop-X415EA-X415EA:~/Téléchargements/asus-touchpad-numpad-driver$ 


up5401ea still missing...

**Comment by kamack38** [comment]
What about `git reset --hard HEAD`?

**Comment by Foul** [comment]
git clone : ok 
sudo ./uninstall.sh ok
sudo ./install.sh ok
no on/off light :( (not working at all)

**Comment by Foul** [comment]
$ sudo -E ./asus_touchpad.py up5401ea 40
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Touched numlock in time:
INFO:Pad:1657720317.427124
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot
INFO:Pad:Started new slot
INFO:Pad:Ended existing slot


No log in /var/log/asus_touchpad_numpad_driver/
and on/off light not working

**Comment by kamack38** [comment]
Did you press the numlock for at least 1 second?

**Comment by kamack38** [comment]
(the top right corner of the touchpad)

**Comment by kamack38** [comment]
> still no return
What do you mean by that?

**Comment by Foul** [comment]
do you have telegram or discorg?

**Comment by kamack38** [comment]
Yup I have discord (Kamack38#8518)

**Comment by ldrahnik** [comment]
@kamack38 @Foul Solved? It might be affected by the last pushed commit with fix when is the keyboard with led indicators not detected. But I only guess because I do not see the detection part of command ```LOG=DEBUG sudo -E ./asus_touchpad.py up5401ea 40```, these rows I miss in your log (my case for example):

```
$ LOG=DEBUG sudo -E ./asus_touchpad.py up5401ea 40
DEBUG:Pad:Detect keyboard from N: Name="AT Translated Set 2 keyboard"
DEBUG:Pad:Set keyboard 3 from H: Handlers=sysrq kbd event3 leds
DEBUG:Pad:Detect touchpad from N: Name="ASUE140D:00 04F3:31B9 Touchpad"
DEBUG:Pad:Set touchpad device id 2 from S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-ASUE140D:00/0018:04F3:31B9.0002/input/input29
DEBUG:Pad:Set touchpad id 12 from H: Handlers=mouse3 event12
DEBUG:Pad:Touchpad min-max: x 0-3880, y 0-2299
DEBUG:Pad:Numpad min-max: x 200-3680, y 200-2219
...
```

But a last sent log seems OK.

**Comment by Foul** [comment]
still not resolved... sorry..

**Comment by ldrahnik** [comment]
Please post the result of the command as I mentioned (do not crop detection part): `LOG=DEBUG sudo -E ./asus_touchpad.py up5401ea 40`. And post the result of the command `sudo libinput debug-events` (I am interested in keyboards and touchpads).

Also, can you connect an external keyboard and confirm the numbers work.
Also, can you add EN keyboard layout (in case you use french) and confirm it happens too, would be nice.

**Comment by Foul** [comment]
14th of July here... not working tomorrow.. will test on Friday ;)

**Comment by ldrahnik** [comment]
That's great. Your last sent debug log was ok, so that was not this driver problem. 

Please restart a laptop and run the command ```sudo systemctl status asus_touchpad_numpad.service``` and pin the result here.

**Comment by ldrahnik** [comment]
I guess it is specific for linux mint. So probably make a script and add that script to the Startup Applications as is recommended [here](https://forums.linuxmint.com/viewtopic.php?t=321591).

**Comment by Foul** [comment]
ExecStartPre=/bin/sleep 60  : system is just longer to boot.. but numpad is not activated

how to make a root script launched at start plz ?

**Comment by Foul** [comment]
Found the solution ! in the service file : instead of Type=simple replace by Type=idle  .. and all is working !

**Comment by ldrahnik** [comment]
@Foul changed permanently to `idle` as it should not be a problem because that type `idle` is similar to `simple`.

**Comment by Foul** [comment]
Hello, the customer to whom I had sold the 14-inch Asus came back for me to install the numad driver as I had done the last time on the one in the store.. and now impossible to have it recognized  I know what else to do... the on/off button lights up by choosing up5401ea as on the other... but no key reacts . The last time, the method with "idle" had worked.. here no... (exactly the same PC)..

Only some keys are working : Backspace, Enter, %, = .. but not 1.2.3.4.5.6.7.8.9

**Comment by ldrahnik** [comment]
Hello, I would like help you but I do not know a lot about laptop where driver does not work. Latest master I can confirm for me works. I tried now.

Me be you I would focus on basic informations like distribution, kernel, devices dump (touchpad, keyboard), keyboard layout (en, fr, it, ..), run driver in debug mode and attach driver logs.

**Comment by Foul** [comment]
Yes !! i just upgraded Linux Mint 20.3 to 21.0 and all is working !!!
